[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "quest"
version = "2026.0.1"
authors = [
  { name="A. J. Hedge", email="aj.hedge@icrar.org" },
]
description = "Utilities for scripting or notebooks that are designed to provide a simple interface to query and retrieve astronomical survey data, index alongside local data and perform basic aperture photometry on the 'best' (deepest/high-res) data at multiple wavelengths."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "numpy>=2.5.2",
  "matplotlib>=3.11.1",
  "astropy>=8.0.0",
  "photutils>=3.0.0",
  "astroquery>=0.4.11",
  "pyvo>=1.9.1",
  "requests>=2.34.2",
  "scipy>=1.18.1",
  "reproject>=0.20.0",
  "aiohttp>=3.12.15",
]

[project.urls]
Homepage = "https://github.com/aj-hedge/QUEST"
Repository = "https://github.com/aj-hedge/QUEST.git"
Changelog = "https://github.com/aj-hedge/QUEST/blob/main/CHANGELOG.md"
Issues = "https://github.com/aj-hedge/QUEST/issues"
